version: "3.9"
services: 
  zookeeper:
    image: "bitnami/zookeeper:3.6.3"
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: "bitnami/kafka:2.8.1"
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    
  jupyter:
    build: 
      context: .
      dockerfile: Dockerfile.kafka
    environment:
      - JUPYTER_TOKEN=codeop
    ports:
      - "8888:8888"
    volumes:
      - ./nbs/:/home/jovyan/work
